[DEFAULT]
ARGON_TIME_COST = 2
ARGON_MEMORY_COST = 204800
ARGON_PARALLELISM = 4
ARGON_SALT_LENGTH = 16
ARGON_HASH_LENGTH = 32
[DEV]
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 8000
POSTGRES_MIN_CONNECTIONS = 2
POSTGRES_MAX_CONNECTIONS = 2

[PROD]